# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='Delete_NO',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='things',
            name='Edit_NO',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
