# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20170928_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
